/* confdefs.h */
#define PACKAGE_NAME "erofs-utils"
#define PACKAGE_TARNAME "erofs-utils"
#define PACKAGE_VERSION "1.3"
#define PACKAGE_STRING "erofs-utils 1.3"
#define PACKAGE_BUGREPORT "linux-erofs@lists.ozlabs.org"
#define PACKAGE_URL ""
#define PACKAGE "erofs-utils"
#define VERSION "1.3"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_DIRENT_H 1
#define HAVE_EXECINFO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_GETOPT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LINUX_FALLOC_H 1
#define HAVE_LINUX_FS_H 1
#define HAVE_LINUX_TYPES_H 1
#define HAVE_LINUX_XATTR_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_SYSMACROS_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STRUCT_STAT_ST_RDEV 1
#define HAVE_LSEEK64_PROTOTYPE 1
#define HAVE_BACKTRACE 1
#define HAVE_FALLOCATE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_MEMSET 1
#define HAVE_REALPATH 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRRCHR 1
#define HAVE_STRTOULL 1
#define HAVE_LZ4_H 1
#define HAVE_LIBLZ4 1
#define HAVE_LIBUUID 1
#define LZ4_ENABLED 1
#define LZ4HC_ENABLED 1
